### PR TITLE
many improvements : UI, sort files, config file names

### PR DESCRIPTION
**Pull request by pafontai**
I'm new to github, so I made a mistake : no branch to isolate each development.

There are the improvements (I think so) : 
- UI of audio and video format in download tab
- adding some config properties : youtubedl command parameters, file name config, subfolder config
- read recursively the target folder to display music and video files + sort list
- ability to filter downloaded files list
- display all logs into the same browser window by default
- redirect stderr of youtubedl command into log file

### CODE REVIEW

**Comment by DavidTre07** [comment]
Hi @pafontai ,
not sure Uli will integrate your pull request as I submitted one pull request 7 months ago without integration...
I think we have to fork.
David.

**Comment by hukoeth** [comment]
Hey, Sorry have been super busy lately and not really monitoring Github. I'm happy to look at your pull requests this weekend although I think this code needs a rewrite.
If you want to make a full fledged project out of this please feel free to fork as well. I don't mind.
@DavidTre07 I must have overlooked your PR, sorry.

**Comment by DavidTre07** [comment]
@hukoeth happy to read you !
No I don't want someone make a fork, just I was thinking you are not interrested anymore to accept pull request so the only solution was to fork.
But if you agree to merge no problem to stay on your repository :)
Thanks !

**Comment by DavidTre07** [comment]
Seems you not merged the PR...

**Pull request merged**
